### ISSUE TITLE
Typos in when importing public key from signer's certificate

### ISSUE THREAD

**Issue by abgoldberg** [PeculiarVentures/pkijs-es6#6] opened 2016-09-20 16:11 UTC
(Same issue reported in non-es6 version appears to still be present)

In the code that imports the public key from signer's certificate, it should be checking the signerCertificate.subjectPublicKeyInfo.algorithm instead of signerCertificate.signatureAlgorithm. In my example, the former is RSA and the latter is ECDSA, so checking the wrong algorithm here leads into the special case for ECDSA which doesn't really apply.

Here's a patch that fixed my immediate problem, but it seems there are a few other places in the code whose comments refer to "public key algorithm" but then assign algorithmObject based on the signature algorithm. I don't know enough about those parts of the code to try to suggest fixes, though.

```
diff --git a/src/SignedData.js b/src/SignedData.js
index 08856dd..ee218e8 100644
--- a/src/SignedData.js
+++ b/src/SignedData.js
@@ -835,7 +835,7 @@ export default class SignedData
                        //endregion

                        //region Get information about public key algorithm and default parameters for import
-                       const algorithmObject = getAlgorithmByOID(signerCertificate.signatureAlgorithm.algorithmId);
+                       const algorithmObject = getAlgorithmByOID(signerCertificate.subjectPublicKeyInfo.algorithm.algorithmId);
                        if(("name" in algorithmObject) === false)
                        {
                                if(extendedMode)
@@ -843,14 +843,14 @@ export default class SignedData
                                        return Promise.reject({
                                                date: checkDate,
                                                code: 11,
-                                               message: `Unsupported public key algorithm: ${signerCertificate.signatureAlgorithm.algorithmId}`,
+                                               message: `Unsupported public key algorithm: ${signerCertificate.subjectPublicKeyInfo.algorithm.algorithmId}`,
                                                signatureVerified: null,
                                                signerCertificate,
                                                signerCertificateVerified: true
                                        });
                                }

-                               return Promise.reject(`Unsupported public key algorithm: ${signerCertificate.signatureAlgorithm.algorithmId}`);
+                               return Promise.reject(`Unsupported public key algorithm: ${signerCertificate.subjectPublicKeyInfo.algorithm.algorithmId}`);
                        }
```

**Comment by YuryStrozhevsky** [comment] 2016-09-20 19:33
Please take a look at my [answer](https://github.com/PeculiarVentures/PKI.js/pull/73) again.

**Comment by rmhrisk** [comment] 2016-09-21 10:01
Closing as a dupe of #6

**Closed** 2016-09-21 15:20 UTC
